name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build App
      run: |
        xcodebuild -project Teximo.xcodeproj \
                   -scheme Teximo \
                   -configuration Release \
                   -derivedDataPath DerivedData \
                   build
                   
    - name: Create DMG
      run: |
        # Find the built app
        APP_PATH=$(find DerivedData -name "*.app" -type d | head -1)
        
        # Create DMG
        mkdir -p dmg_temp
        cp -R "$APP_PATH" dmg_temp/
        ln -s /Applications dmg_temp/Applications
        
        hdiutil create -volname "Teximo" \
                       -srcfolder dmg_temp \
                       -ov -format UDZO \
                       Teximo.dmg
                       
        rm -rf dmg_temp
        
    - name: Upload DMG
      uses: actions/upload-artifact@v4
      with:
        name: Teximo-DMG
        path: Teximo.dmg
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: Teximo.dmg
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
